doctrine:
    dbal:
        types:
            notificationId: App\Infrastructure\Doctrine\DBAL\Type\NotificationIdType
            customerInfo: App\Infrastructure\Doctrine\DBAL\Type\CustomerInfoType
            deliveryInfo: App\Infrastructure\Doctrine\DBAL\Type\DeliveryInfoType
            message: App\Infrastructure\Doctrine\DBAL\Type\MessageType
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Domain:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Mapping'
                prefix: 'App\Domain\Model'
                alias: Domain
            Infrastructure:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Entity'
                prefix: 'App\Infrastructure\Doctrine\Entity'
                alias: Infrastructure
