framework:
  messenger:
    default_bus: command.bus
    buses:
      command.bus:
        middleware:
          - App\Infrastructure\Doctrine\DomainEventEmiterMiddleware
          - App\Infrastructure\Middleware\AuditLogMiddleware
      event.bus:
        middleware:
          - doctrine_ping_connection
          - doctrine_close_connection
          - doctrine_transaction
    transports:
      async:
        dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
        retry_strategy:
          max_retries: 9
          delay: 60000
          multiplier: 2
        options:
          queue_name: async
          auto_setup: false
      failed: '%env(MESSENGER_TRANSPORT_DSN)%?queue_name=failed'
    routing:
      App\Domain\Event\NotificationCreatedEvent: async
